export const photos = [
  {
    id: 0,
    src: "https://source.unsplash.com/2ShvY8Lf6l0/800x599",
    width: 4,
    height: 3,
    thumbnail: "A URL to load a low quality image from",
    metaData: {
      origin: "customer web portal",
      customerName: "usman",
      uplaodedDate: "7/5/2020, 7:20 P.M.",
    },
    notes: "Hi Pakistan",
    tags: ["ali", "hamza", "tufail"],
  },
  {
    id: 1,
    src: "https://source.unsplash.com/Dm-qxdynoEc/800x799",
    width: 1,
    height: 1,
    metaData: {
      origin: "Ignition",
      customerName: "zain",
      uplaodedDate: "10/5/2020. 7:20 P.M.",
    },
    notes: "Hi, Lahore",
    tags: ["usman", "adeel", "husnain"],
  },
  {
    id: 2,
    src: "https://source.unsplash.com/qDkso9nvCg0/600x799",
    width: 3,
    height: 4,
    metaData: {
      origin: "Lahore",
      customerName: "hamid",
      uplaodedDate: "21/5/2020. 7:20 P.M.",
    },
    notes: "Hi london",
    tags: ["ghani", "gujjar", "NUCES"],
  },
  {
    id: 3,
    src: "https://source.unsplash.com/iecJiKe_RNg/600x799",
    width: 3,
    height: 4,
    metaData: {
      origin: "Trump",
      customerName: "mustafa",
      uplaodedDate: "10/5/2020. 7:20 P.M.",
    },
    notes: "Hi Islamabad",
    tags: ["Usman", "Ahmed", "Faizan"],
  },
  {
    id: 4,
    src: "https://source.unsplash.com/epcsn8Ed8kY/600x799",
    width: 3,
    height: 4,
    metaData: {
      origin: "Obama",
      customerName: "hassan",
      uplaodedDate: "10/5/2020. 7:20 P.M.",
    },
    notes: "Hi KPK",
    tags: ["Coke Studio", "Azadi"],
  },
  {
    id: 5,
    src: "https://source.unsplash.com/NQSWvyVRIJk/800x599",
    width: 4,
    height: 3,
    metaData: {
      origin: "SRK",
      customerName: "gujjar",
      uplaodedDate: "10/5/2020. 7:20 P.M.",
    },
    notes: "boris",
    tags: ["cricket", "Hockey"],
  },
  {
    id: 6,
    src: "https://source.unsplash.com/zh7GEuORbUw/600x799",
    width: 3,
    height: 4,
    metaData: {
      origin: "lol",
      customerName: "balaj",
      uplaodedDate: "10/5/2020. 7:20 P.M.",
    },
    notes: "",
  },
  {
    id: 7,
    src: "https://source.unsplash.com/PpOHJezOalU/800x599",
    width: 4,
    height: 3,
    metaData: {
      origin: "origin",
      customerName: "mubeen",
      uplaodedDate: "10/5/2020. 7:20 P.M.",
    },
    notes: "",
  },
  {
    id: 8,
    src: "https://source.unsplash.com/I1ASdgphUH4/800x599",
    width: 4,
    height: 3,
    metaData: {
      origin: "boris",
      customerName: "junaid",
      uplaodedDate: "10/5/2020. 7:20 P.M.",
    },
    notes: "",
  },
];
